<?php
// includes/lang.php - Translation Dictionary

$lang = [
    'en' => [
        'Home' => 'Home', 'Profile' => 'Profile', 'Add Listing' => 'Add Listing',
        'Admin Panel' => 'Admin Panel', 'Logout' => 'Logout', 'Login' => 'Login',
        'Register' => 'Register', 'Rently - Smart Rental Platform' => 'Rently - Smart Rental Platform',
        'Find What You Need' => 'Find What You Need, Rent It Easy.',
        'Cars, Apartments' => 'Cars, Apartments, Equipment & More.',
        'Search keyword...' => 'Search keyword...', 'All Categories' => 'All Categories',
        'All Cities' => 'All Cities', 'Newest First' => 'Newest First',
        'Price: Low to High' => 'Price: Low to High', 'Price: High to Low' => 'Price: High to Low',
        'Search' => 'Search', 'View Details' => 'View Details',
        'No listings found.' => 'No listings found.',
        'Try adjusting' => 'Try adjusting your search filters.',
        'My Profile' => 'My Profile', 'Name' => 'Name:', 'Email' => 'Email:',
        'Phone' => 'Phone:', 'My Bookings' => 'My Bookings', 'My Listings' => 'My Listings',
        'Add New Listing' => 'Add New Listing',
        'Rent out your items' => 'Rent out your items to others securely.',
        'Title' => 'Title', 'Category' => 'Category', 'City' => 'City',
        'Price Per Day' => 'Price Per Day (₪)', 'Price' => 'Price', 'Per' => 'Per',
        'Day' => 'Day', 'Hour' => 'Hour',
        'Description' => 'Description', 'Image Upload' => 'Image Upload (Max 2MB)',
        'Admin Dashboard' => 'Admin Dashboard',
        'Manage listings' => 'Manage listings, users, and monitor platform activity.',
        'Approve' => 'Approve', 'Delete' => 'Delete', 'Listing Details' => 'Listing Details',
        'Owner' => 'Owner', 'Status' => 'Status', 'Actions' => 'Actions',
        'Create an Account' => 'Create an Account', 'Join Rently today!' => 'Join Rently today!',
        'Full Name' => 'Full Name', 'Email Address' => 'Email Address', 'Password' => 'Password',
        'Sign Up' => 'Sign Up', 'Already have an account?' => 'Already have an account?',
        'Verification' => 'Verification',
        'Enter the code we "sent" you.' => 'Enter the code we "sent" you.',
        'Verification Code' => 'Verification Code', 'Verify & Login' => 'Verify & Login',
        'Welcome Back' => 'Welcome Back',
        'Login to your Rently account.' => 'Login to your Rently account.',
        '2-Step Verification' => '2-Step Verification',
        "Don't have an account?" => "Don't have an account?",
        'Book this item' => 'Book this item', 'From Date' => 'From Date:',
        'To Date' => 'To Date:', 'Confirm Booking' => 'Confirm Booking',
        'Hosted by' => 'Hosted by', 'Pending' => 'Pending', 'Approved' => 'Approved',
        'Quick Links' => 'Quick Links', 'Contact Us' => 'Contact Us',
        'Reviews' => 'Reviews', 'Leave a Review' => 'Leave a Review',
        'Rating' => 'Rating', 'Your Comment' => 'Your Comment',
        'Submit Review' => 'Submit Review', 'No reviews yet.' => 'No reviews yet.',
        'Admins cannot book or review items.' => 'Admins cannot book or review items.',
        'Rejected' => 'Rejected', 'Cancel' => 'Cancel',
        'Booking Requests' => 'Booking Requests', 'Reject' => 'Reject',
        'Booking approved!' => 'Booking approved!',
        'Edit Profile' => 'Edit Profile', 'Bio' => 'Bio', 'Profile Picture' => 'Profile Picture',
        'Save Changes' => 'Save Changes', 'Profile updated successfully!' => 'Profile updated successfully!',
        'No bio yet.' => 'No bio yet.',
        'Edit' => 'Edit', 'Edit Listing' => 'Edit Listing',
        'Upload New Image (optional)' => 'Upload New Image (optional)',
        'Listing updated successfully!' => 'Listing updated successfully!',
        'No bookings yet.' => 'No bookings yet.', 'No listings yet.' => 'No listings yet.',
        'Add one!' => 'Add one!',
        'Checkout' => 'Checkout', 'Payment Details' => 'Payment Details',
        'Cardholder Name' => 'Cardholder Name', 'Card Number' => 'Card Number',
        'Expiry Date' => 'Expiry Date', 'Pay' => 'Pay', 'Total' => 'Total',
        'Secure payment simulation for demo purposes.' => 'Secure payment simulation for demo purposes.',
        'Booking Submitted!' => 'Booking Submitted!',
        'Your booking request has been sent to the owner for approval.' => 'Your booking request has been sent to the owner for approval.',
        'View My Bookings' => 'View My Bookings',
        'Please fill all payment fields.' => 'Please fill all payment fields.',
        'Invalid card number.' => 'Invalid card number.',
        'These dates are no longer available. Someone booked them just now!' => 'These dates are no longer available!',
        'Proceed to Checkout' => 'Proceed to Checkout',
        'Sorry, these dates are already booked!' => 'Sorry, these dates are already booked!',
        'End date must be after start date.' => 'End date must be after start date.',
        'Please login to book.' => 'Please login to book this item.',
        'Forgot Password' => 'Forgot Password', 'Forgot Password?' => 'Forgot Password?',
        'Enter your email to receive a reset code.' => 'Enter your email to receive a reset code.',
        'Send Reset Code' => 'Send Reset Code', 'Back to Login' => 'Back to Login',
        'Reset Password' => 'Reset Password', 'New Password' => 'New Password',
        'Password Updated!' => 'Password Updated!',
        'Password reset successfully!' => 'Password reset successfully!',
        'No account found with that email.' => 'No account found with that email.',
        'Invalid reset code.' => 'Invalid reset code.',
        'My Favorites' => 'My Favorites', 'No favorites yet.' => 'No favorites yet.',
        'Browse listings and click the heart icon to save items here.' => 'Browse listings and click the heart icon to save items here.',
        'Browse Listings' => 'Browse Listings', 'Add to Favorites' => 'Add to Favorites',
        'Remove' => 'Remove',
        'You May Also Like' => 'You May Also Like', 'Location' => 'Location',
        '/ day' => '/ day', '/ hour' => '/ hour', 'days' => 'days', 'hours' => 'hours',
        'Check-in' => 'Check-in', 'Check-out' => 'Check-out',
        'Min ₪' => 'Min ₪', 'Max ₪' => 'Max ₪',
        'Users' => 'Users', 'Listings' => 'Listings', 'Bookings' => 'Bookings',
        'Revenue' => 'Revenue', 'Block' => 'Block', 'Unblock' => 'Unblock',
        'Role' => 'Role', 'Image' => 'Image',
        'Your account has been blocked. Contact support.' => 'Your account has been blocked. Contact support.',
        'Invalid email or password.' => 'Invalid email or password.',
        'Invalid verification code!' => 'Invalid verification code!',
        'Review added successfully!' => 'Review added successfully!',
        'Failed to add review.' => 'Failed to add review.',
        'Listing added successfully! Waiting for admin approval.' => 'Listing added! Waiting for admin approval.',
        'The smart way to rent anything. Cars, apartments, equipment and more — all in one platform.' => 'The smart way to rent anything. Cars, apartments, equipment and more — all in one platform.',
        'Categories' => 'Categories',
        'Show Filters' => 'Show Filters', 'Hide Filters' => 'Hide Filters',
        'Apply Filters' => 'Apply Filters', 'Sort' => 'Sort',
        'results found' => 'results found',
        'Renter' => 'Renter', 'Dates' => 'Dates', 'Amount' => 'Amount',
    ],
    'he' => [
        'Home' => 'ראשי', 'Profile' => 'פרופיל', 'Add Listing' => 'הוסף פריט',
        'Admin Panel' => 'פאנל ניהול', 'Logout' => 'התנתק', 'Login' => 'התחבר',
        'Register' => 'הירשם', 'Rently - Smart Rental Platform' => 'רנטלי - פלטפורמת השכרה חכמה',
        'Find What You Need' => 'מצא בדיוק את מה שאתה צריך.',
        'Cars, Apartments' => 'רכבים, דירות, ציוד ועוד.',
        'Search keyword...' => 'חיפוש...', 'All Categories' => 'כל הקטגוריות',
        'All Cities' => 'כל הערים', 'Newest First' => 'החדשים ביותר',
        'Price: Low to High' => 'מחיר: מהנמוך לגבוה',
        'Price: High to Low' => 'מחיר: מהגבוה לנמוך',
        'Search' => 'חפש', 'View Details' => 'צפה בפרטים',
        'No listings found.' => 'לא נמצאו פריטים.',
        'Try adjusting' => 'נסה לשנות את מסנני החיפוש.',
        'My Profile' => 'הפרופיל שלי', 'Name' => 'שם:', 'Email' => 'אימייל:',
        'Phone' => 'טלפון:', 'My Bookings' => 'ההזמנות שלי', 'My Listings' => 'הפריטים שלי',
        'Add New Listing' => 'הוסף פריט חדש',
        'Rent out your items' => 'השכר את הפריטים שלך בבטחה.',
        'Title' => 'כותרת', 'Category' => 'קטגוריה', 'City' => 'עיר',
        'Price Per Day' => 'מחיר ליום (₪)', 'Price' => 'מחיר', 'Per' => 'לפי',
        'Day' => 'יום', 'Hour' => 'שעה',
        'Description' => 'תיאור', 'Image Upload' => 'העלאת תמונה (עד 2MB)',
        'Admin Dashboard' => 'לוח בקרה ניהולי',
        'Manage listings' => 'נהל פריטים, משתמשים ופעילות הפלטפורמה.',
        'Approve' => 'אשר', 'Delete' => 'מחק', 'Listing Details' => 'פרטי הפריט',
        'Owner' => 'בעלים', 'Status' => 'סטטוס', 'Actions' => 'פעולות',
        'Create an Account' => 'צור חשבון', 'Join Rently today!' => 'הצטרף לרנטלי עוד היום!',
        'Full Name' => 'שם מלא', 'Email Address' => 'כתובת אימייל', 'Password' => 'סיסמה',
        'Sign Up' => 'הרשמה', 'Already have an account?' => 'כבר יש לך חשבון?',
        'Verification' => 'אימות',
        'Enter the code we "sent" you.' => 'הזן את הקוד ש"שלחנו" לך.',
        'Verification Code' => 'קוד אימות', 'Verify & Login' => 'אימות והתחברות',
        'Welcome Back' => 'ברוך שובך',
        'Login to your Rently account.' => 'התחבר לחשבון הרנטלי שלך.',
        '2-Step Verification' => 'אימות דו-שלבי',
        "Don't have an account?" => 'אין לך חשבון?',
        'Book this item' => 'הזמן פריט זה', 'From Date' => 'מתאריך:',
        'To Date' => 'עד תאריך:', 'Confirm Booking' => 'אשר הזמנה',
        'Hosted by' => 'באירוח של', 'Pending' => 'ממתין', 'Approved' => 'מאושר',
        'Quick Links' => 'קישורים מהירים', 'Contact Us' => 'צור קשר',
        'Reviews' => 'ביקורות', 'Leave a Review' => 'כתוב ביקורת',
        'Rating' => 'דירוג', 'Your Comment' => 'התגובה שלך',
        'Submit Review' => 'שלח ביקורת', 'No reviews yet.' => 'אין ביקורות עדיין.',
        'Admins cannot book or review items.' => 'מנהלים אינם יכולים להזמין או לכתוב ביקורות.',
        'Rejected' => 'נדחה', 'Cancel' => 'בטל',
        'Booking Requests' => 'בקשות הזמנה', 'Reject' => 'דחה',
        'Booking approved!' => 'ההזמנה אושרה!',
        'Edit Profile' => 'ערוך פרופיל', 'Bio' => 'אודות', 'Profile Picture' => 'תמונת פרופיל',
        'Save Changes' => 'שמור שינויים', 'Profile updated successfully!' => 'הפרופיל עודכן בהצלחה!',
        'No bio yet.' => 'אין ביוגרפיה עדיין.',
        'Edit' => 'ערוך', 'Edit Listing' => 'ערוך פריט',
        'Upload New Image (optional)' => 'העלה תמונה חדשה (אופציונלי)',
        'Listing updated successfully!' => 'הפריט עודכן בהצלחה!',
        'No bookings yet.' => 'אין הזמנות עדיין.', 'No listings yet.' => 'אין פריטים עדיין.',
        'Add one!' => 'הוסף אחד!',
        'Checkout' => 'תשלום', 'Payment Details' => 'פרטי תשלום',
        'Cardholder Name' => 'שם בעל הכרטיס', 'Card Number' => 'מספר כרטיס',
        'Expiry Date' => 'תאריך תפוגה', 'Pay' => 'שלם', 'Total' => 'סה"כ',
        'Secure payment simulation for demo purposes.' => 'סימולציית תשלום מאובטחת למטרות הדגמה.',
        'Booking Submitted!' => 'ההזמנה נשלחה!',
        'Your booking request has been sent to the owner for approval.' => 'בקשת ההזמנה שלך נשלחה לבעלים לאישור.',
        'View My Bookings' => 'צפה בהזמנות שלי',
        'Please fill all payment fields.' => 'מלא את כל שדות התשלום.',
        'Invalid card number.' => 'מספר כרטיס לא תקין.',
        'These dates are no longer available. Someone booked them just now!' => 'התאריכים כבר לא זמינים!',
        'Proceed to Checkout' => 'המשך לתשלום',
        'Sorry, these dates are already booked!' => 'סליחה, תאריכים אלו כבר תפוסים!',
        'End date must be after start date.' => 'תאריך הסיום חייב להיות אחרי תאריך ההתחלה.',
        'Please login to book.' => 'אנא התחבר כדי להזמין.',
        'Forgot Password' => 'שכחתי סיסמה', 'Forgot Password?' => 'שכחת סיסמה?',
        'Enter your email to receive a reset code.' => 'הזן את האימייל שלך לקבלת קוד איפוס.',
        'Send Reset Code' => 'שלח קוד איפוס', 'Back to Login' => 'חזור להתחברות',
        'Reset Password' => 'איפוס סיסמה', 'New Password' => 'סיסמה חדשה',
        'Password Updated!' => 'הסיסמה עודכנה!',
        'Password reset successfully!' => 'הסיסמה אופסה בהצלחה!',
        'No account found with that email.' => 'לא נמצא חשבון עם אימייל זה.',
        'Invalid reset code.' => 'קוד איפוס לא תקין.',
        'My Favorites' => 'המועדפים שלי', 'No favorites yet.' => 'אין מועדפים עדיין.',
        'Browse listings and click the heart icon to save items here.' => 'עיין בפריטים ולחץ על הלב כדי לשמור כאן.',
        'Browse Listings' => 'עיין בפריטים', 'Add to Favorites' => 'הוסף למועדפים',
        'Remove' => 'הסר',
        'You May Also Like' => 'אולי יעניין אותך גם', 'Location' => 'מיקום',
        '/ day' => '/ יום', '/ hour' => '/ שעה', 'days' => 'ימים', 'hours' => 'שעות',
        'Check-in' => 'כניסה', 'Check-out' => 'יציאה',
        'Min ₪' => 'מינימום ₪', 'Max ₪' => 'מקסימום ₪',
        'Users' => 'משתמשים', 'Listings' => 'פריטים', 'Bookings' => 'הזמנות',
        'Revenue' => 'הכנסות', 'Block' => 'חסום', 'Unblock' => 'בטל חסימה',
        'Role' => 'תפקיד', 'Image' => 'תמונה',
        'Your account has been blocked. Contact support.' => 'החשבון שלך נחסם. צור קשר עם התמיכה.',
        'Invalid email or password.' => 'אימייל או סיסמה שגויים.',
        'Invalid verification code!' => 'קוד אימות שגוי!',
        'Review added successfully!' => 'הביקורת נוספה בהצלחה!',
        'Failed to add review.' => 'נכשל בהוספת ביקורת.',
        'Listing added successfully! Waiting for admin approval.' => 'הפריט נוסף! ממתין לאישור מנהל.',
        'The smart way to rent anything. Cars, apartments, equipment and more — all in one platform.' => 'הדרך החכמה לשכור הכל. רכבים, דירות, ציוד ועוד — הכל בפלטפורמה אחת.',
        'Categories' => 'קטגוריות',
        'Show Filters' => 'הצג מסננים', 'Hide Filters' => 'הסתר מסננים',
        'Apply Filters' => 'החל מסננים', 'Sort' => 'מיון',
        'results found' => 'תוצאות נמצאו',
        'Renter' => 'שוכר', 'Dates' => 'תאריכים', 'Amount' => 'סכום',
    ]
];
?>
