<?php
// includes/lang.php - Translation Dictionary

$lang = [
    'en' => [
        'Cars' => 'Cars', 'Apartments' => 'Apartments', 'Equipment' => 'Equipment',
        'Electronics' => 'Electronics', 'Sports field' => 'Sports field',
        'Home' => 'Home', 'Profile' => 'Profile', 'Add Listing' => 'Add Listing',
        'Admin Panel' => 'Admin Panel', 'Logout' => 'Logout', 'Login' => 'Login',
        'Register' => 'Register', 'Rently - Smart Rental Platform' => 'Rently - Smart Rental Platform',
        'Find What You Need' => 'Find What You Need, Rent It Easy.',
        'Cars, Apartments' => 'Cars, Apartments, Equipment & More.',
        'Search keyword...' => 'Search keyword...', 'All Categories' => 'All Categories',
        'All Cities' => 'All Cities', 'Newest First' => 'Newest First',
        'Price: Low to High' => 'Price: Low to High', 'Price: High to Low' => 'Price: High to Low',
        'Search' => 'Search', 'View Details' => 'View Details',
        'No listings found.' => 'No listings found.',
        'Try adjusting' => 'Try adjusting your search filters.',
        'My Profile' => 'My Profile', 'Name' => 'Name:', 'Email' => 'Email:',
        'Phone' => 'Phone:', 'My Bookings' => 'My Bookings', 'My Listings' => 'My Listings',
        'Add New Listing' => 'Add New Listing',
        'Rent out your items' => 'Rent out your items to others securely.',
        'Title' => 'Title', 'Category' => 'Category', 'City' => 'City',
        'Price Per Day' => 'Price Per Day (₪)', 'Price' => 'Price', 'Per' => 'Per',
        'Day' => 'Day', 'Hour' => 'Hour',
        'Description' => 'Description', 'Image Upload' => 'Image Upload (Max 2MB)',
        'Admin Dashboard' => 'Admin Dashboard',
        'Manage listings' => 'Manage listings, users, and monitor platform activity.',
        'Approve' => 'Approve', 'Delete' => 'Delete', 'Listing Details' => 'Listing Details',
        'Owner' => 'Owner', 'Status' => 'Status', 'Actions' => 'Actions',
        'Create an Account' => 'Create an Account', 'Join Rently today!' => 'Join Rently today!',
        'Full Name' => 'Full Name', 'Email Address' => 'Email Address', 'Password' => 'Password',
        'Sign Up' => 'Sign Up', 'Already have an account?' => 'Already have an account?',
        'Verification' => 'Verification',
        'Enter the code we "sent" you.' => 'Enter the code we "sent" you.',
        'Verification Code' => 'Verification Code', 'Verify & Login' => 'Verify & Login',
        'Welcome Back' => 'Welcome Back',
        'Login to your Rently account.' => 'Login to your Rently account.',
        '2-Step Verification' => '2-Step Verification',
        "Don't have an account?" => "Don't have an account?",
        'Book this item' => 'Book this item', 'From Date' => 'From Date:',
        'To Date' => 'To Date:', 'Confirm Booking' => 'Confirm Booking',
        'Hosted by' => 'Hosted by', 'Pending' => 'Pending', 'Approved' => 'Approved',
        'Quick Links' => 'Quick Links', 'Contact Us' => 'Contact Us',
        'Reviews' => 'Reviews', 'Leave a Review' => 'Leave a Review',
        'Rating' => 'Rating', 'Your Comment' => 'Your Comment',
        'Submit Review' => 'Submit Review', 'No reviews yet.' => 'No reviews yet.',
        'Admins cannot book or review items.' => 'Admins cannot book or review items.',
        'Rejected' => 'Rejected', 'Cancel' => 'Cancel',
        'Booking Requests' => 'Booking Requests', 'Reject' => 'Reject',
        'Booking approved!' => 'Booking approved!',
        'Edit Profile' => 'Edit Profile', 'Bio' => 'Bio', 'Profile Picture' => 'Profile Picture',
        'Save Changes' => 'Save Changes', 'Profile updated successfully!' => 'Profile updated successfully!',
        'No bio yet.' => 'No bio yet.',
        'Edit' => 'Edit', 'Edit Listing' => 'Edit Listing',
        'Upload New Image (optional)' => 'Upload New Image (optional)',
        'Listing updated successfully!' => 'Listing updated successfully!',
        'No bookings yet.' => 'No bookings yet.', 'No listings yet.' => 'No listings yet.',
        'Add one!' => 'Add one!',
        'Checkout' => 'Checkout', 'Payment Details' => 'Payment Details',
        'Cardholder Name' => 'Cardholder Name', 'Card Number' => 'Card Number',
        'Expiry Date' => 'Expiry Date', 'Pay' => 'Pay', 'Total' => 'Total',
        'Secure payment simulation for demo purposes.' => 'Secure payment simulation for demo purposes.',
        'Booking Submitted!' => 'Booking Submitted!',
        'Your booking request has been sent to the owner for approval.' => 'Your booking request has been sent to the owner for approval.',
        'View My Bookings' => 'View My Bookings',
        'Please fill all payment fields.' => 'Please fill all payment fields.',
        'Invalid card number.' => 'Invalid card number.',
        'These dates are no longer available. Someone booked them just now!' => 'These dates are no longer available!',
        'Proceed to Checkout' => 'Proceed to Checkout',
        'Sorry, these dates are already booked!' => 'Sorry, these dates are already booked!',
        'End date must be after start date.' => 'End date must be after start date.',
        'Please login to book.' => 'Please login to book this item.',
        'Forgot Password' => 'Forgot Password', 'Forgot Password?' => 'Forgot Password?',
        'Enter your email to receive a reset code.' => 'Enter your email to receive a reset code.',
        'Send Reset Code' => 'Send Reset Code', 'Back to Login' => 'Back to Login',
        'Reset Password' => 'Reset Password', 'New Password' => 'New Password',
        'Password Updated!' => 'Password Updated!',
        'Password reset successfully!' => 'Password reset successfully!',
        'No account found with that email.' => 'No account found with that email.',
        'Invalid reset code.' => 'Invalid reset code.',
        'My Favorites' => 'My Favorites', 'No favorites yet.' => 'No favorites yet.',
        'Browse listings and click the heart icon to save items here.' => 'Browse listings and click the heart icon to save items here.',
        'Browse Listings' => 'Browse Listings', 'Add to Favorites' => 'Add to Favorites',
        'Remove' => 'Remove',
        'You May Also Like' => 'You May Also Like', 'Location' => 'Location',
        '/ day' => '/ day', '/ hour' => '/ hour', 'days' => 'days', 'hours' => 'hours',
        'Check-in' => 'Check-in', 'Check-out' => 'Check-out',
        'Min ₪' => 'Min ₪', 'Max ₪' => 'Max ₪',
        'Users' => 'Users', 'Listings' => 'Listings', 'Bookings' => 'Bookings',
        'Revenue' => 'Revenue', 'Block' => 'Block', 'Unblock' => 'Unblock',
        'Role' => 'Role', 'Image' => 'Image',
        'Your account has been blocked. Contact support.' => 'Your account has been blocked. Contact support.',
        'Invalid email or password.' => 'Invalid email or password.',
        'Invalid verification code!' => 'Invalid verification code!',
        'Review added successfully!' => 'Review added successfully!',
        'Failed to add review.' => 'Failed to add review.',
        'Listing added successfully! Waiting for admin approval.' => 'Listing added! Waiting for admin approval.',
        'The smart way to rent anything. Cars, apartments, equipment and more — all in one platform.' => 'The smart way to rent anything. Cars, apartments, equipment and more — all in one platform.',
        'Categories' => 'Categories',
        'Show Filters' => 'Show Filters', 'Hide Filters' => 'Hide Filters',
        'Apply Filters' => 'Apply Filters', 'Sort' => 'Sort',
        'results found' => 'results found',
        'Renter' => 'Renter', 'Dates' => 'Dates', 'Amount' => 'Amount',
        'Filter by Date' => 'Filter by Date', 'All Time' => 'All Time', 'Today' => 'Today',
        'Last 7 Days' => 'Last 7 Days', 'Last 30 Days' => 'Last 30 Days', 'Last Year' => 'Last Year',
        'Custom' => 'Custom', 'Start Date' => 'Start Date', 'End Date' => 'End Date', 'Apply' => 'Apply',
        'A login verification code has been sent to your email.' => 'A login verification code has been sent to your email.',
        'A password reset code has been sent to your email.' => 'A password reset code has been sent to your email.',
        'A verification code has been sent to your email.' => 'A verification code has been sent to your email.',
        'Accept' => 'Accept', 'Active Bookings' => 'Active Bookings',
        'Admins cannot book items.' => 'Admins cannot book items.',
        'Admins cannot leave reviews.' => 'Admins cannot leave reviews.',
        'All caught up!' => 'All caught up!', 'Analytics' => 'Analytics',
        'Answered' => 'Answered', 'Any' => 'Any',
        'Appeal Reports' => 'Appeal Reports',
        'Appeal submitted successfully as a support ticket.' => 'Appeal submitted successfully as a support ticket.',
        'Are you sure you want to cancel this booking?' => 'Are you sure you want to cancel this booking?',
        'Are you sure you want to delete all reports for this listing?' => 'Are you sure you want to delete all reports for this listing?',
        'Are you sure you want to delete this listing?' => 'Are you sure you want to delete this listing?',
        'Avatar Upload' => 'Avatar Upload', 'Back' => 'Back',
        'Because these dates/times are pending approval, you joined the waitlist. If they become available, your slot will promote automatically.' => 'Because these dates/times are pending approval, you joined the waitlist. If they become available, your slot will promote automatically.',
        'Bio / Description' => 'Bio / Description',
        'Booking approved to pending owner.' => 'Booking approved to pending owner.',
        'Booking cancelled successfully.' => 'Booking cancelled successfully.',
        'Booking rejected.' => 'Booking rejected.',
        'Booking request approved!' => 'Booking request approved!',
        'Booking request rejected.' => 'Booking request rejected.',
        'Bookings Distribution' => 'Bookings Distribution',
        'Brief summary of the issue...' => 'Brief summary of the issue...',
        'CSRF token verification failed.' => 'CSRF token verification failed.',
        'Cancel Booking' => 'Cancel Booking',
        'Cannot accept. Overlapping dates/hours have already been approved!' => 'Cannot accept. Overlapping dates/hours have already been approved!',
        'Car Make' => 'Car Make', 'Category Share' => 'Category Share',
        'Close Ticket' => 'Close Ticket', 'Close this ticket?' => 'Close this ticket?',
        'Closed' => 'Closed',
        'Contact details are private and will be visible once you have an approved booking with this user.' => 'Contact details are private and will be visible once you have an approved booking with this user.',
        'Copied!' => 'Copied!',
        'Current Additional Images' => 'Current Additional Images', 'Current Image' => 'Current Image',
        'Database error: ' => 'Database error: ', 'Date' => 'Date',
        'Delete Reports' => 'Delete Reports',
        'Describe your problem in detail...' => 'Describe your problem in detail...',
        'Dismiss' => 'Dismiss',
        'Duplicate email. This email is already registered.' => 'Duplicate email. This email is already registered.',
        'Electronics Brand' => 'Electronics Brand', 'End Time' => 'End Time',
        'End time/date must be after start time/date.' => 'End time/date must be after start time/date.',
        'Enter the code we sent you.' => 'Enter the code we sent you.',
        'Equipment Brand' => 'Equipment Brand',
        'Failed to copy link.' => 'Failed to copy link.',
        'Failed to move uploaded file.' => 'Failed to move uploaded file.',
        'Failed to process booking. Database error: ' => 'Failed to process booking. Database error: ',
        'Failed to save listing. Database error: ' => 'Failed to save listing. Database error: ',
        'Failed to send verification email. Please contact support.' => 'Failed to send verification email. Please contact support.',
        'Failed to submit appeal.' => 'Failed to submit appeal.',
        'Failed to submit report.' => 'Failed to submit report.',
        'Failed to update profile.' => 'Failed to update profile.',
        'Go to My Listings' => 'Go to My Listings',
        'Hello! I am the Rently Assistant. How can I help you today?' => 'Hello! I am the Rently Assistant. How can I help you today?',
        'Here is your verification code:' => 'Here is your verification code:',
        'How do I book?' => 'How do I book?', 'How do I contact admin?' => 'How do I contact admin?',
        'If you need admin help, please open a Support Ticket from your Profile or the top menu!' => 'If you need admin help, please open a Support Ticket from your Profile or the top menu!',
        'Image deleted successfully.' => 'Image deleted successfully.',
        'Image is too large. Max 2MB.' => 'Image is too large. Max 2MB.',
        'Image not found.' => 'Image not found.',
        'Incoming Booking Requests' => 'Incoming Booking Requests',
        'Invalid email.' => 'Invalid email.',
        'Invalid expiry date. Please use the MM/YY format.' => 'Invalid expiry date. Please use the MM/YY format.',
        'Invalid image format. Only JPG, PNG, and WebP are allowed.' => 'Invalid image format. Only JPG, PNG, and WebP are allowed.',
        'Invalid phone number. It must be exactly 10 digits.' => 'Invalid phone number. It must be exactly 10 digits.',
        'Listing approved.' => 'Listing approved.',
        'Listing deactivated (historical booking data preserved).' => 'Listing deactivated (historical booking data preserved).',
        'Listing deactivated (history preserved).' => 'Listing deactivated (history preserved).',
        'Listing deleted successfully.' => 'Listing deleted successfully.', 'Listing deleted.' => 'Listing deleted.',
        'Listing updated successfully! Status reset to pending for admin approval.' => 'Listing updated successfully! Status reset to pending for admin approval.',
        'Manage systems' => 'Manage systems', 'Mark all as read' => 'Mark all as read',
        'Message' => 'Message', 'Min Rooms' => 'Min Rooms',
        'Most Active Renters' => 'Most Active Renters',
        'My Support Tickets' => 'My Support Tickets', 'My Tickets' => 'My Tickets',
        'Name and Email cannot be empty.' => 'Name and Email cannot be empty.',
        'Need help?' => 'Need help?', 'New %s' => 'New %s',
        'No bio provided.' => 'No bio provided.',
        'No bookings found matching these criteria.' => 'No bookings found matching these criteria.',
        'No incoming booking requests.' => 'No incoming booking requests.',
        'No listings found matching these criteria.' => 'No listings found matching these criteria.',
        'No reports found matching these criteria.' => 'No reports found matching these criteria.',
        'No support tickets found matching these criteria.' => 'No support tickets found matching these criteria.',
        'No users found matching these criteria.' => 'No users found matching these criteria.',
        'Notifications' => 'Notifications',
        'Occupied hours on this date:' => 'Occupied hours on this date:',
        'Open' => 'Open', 'Open Support Center' => 'Open Support Center',
        'Open a New Ticket' => 'Open a New Ticket', 'Opened on' => 'Opened on',
        'Owner Contact Information:' => 'Owner Contact Information:',
        'Password must be at least 6 characters.' => 'Password must be at least 6 characters.',
        'Past Bookings' => 'Past Bookings', 'Phone Number' => 'Phone Number',
        'Please upload an image.' => 'Please upload an image.',
        'Price must be a positive number.' => 'Price must be a positive number.',
        'Profile Settings' => 'Profile Settings',
        'Profile updated successfully.' => 'Profile updated successfully.',
        'Rating must be between 1 and 5.' => 'Rating must be between 1 and 5.',
        'Reject this booking?' => 'Reject this booking?', 'Remove from favorites?' => 'Remove from favorites?',
        'Renter Contact Information:' => 'Renter Contact Information:',
        'Report Listing' => 'Report Listing', 'Report dismissed.' => 'Report dismissed.',
        'Report marked as resolved.' => 'Report marked as resolved.',
        'Report submitted successfully.' => 'Report submitted successfully.',
        'Report this Listing' => 'Report this Listing', 'Reported' => 'Reported', 'Reports' => 'Reports',
        'Required field missing.' => 'Required field missing.', 'Resolve' => 'Resolve',
        'Save Profile Settings' => 'Save Profile Settings', 'Search Results' => 'Search Results',
        'Select Date' => 'Select Date',
        'Selected images must be chosen again if restoring a draft.' => 'Selected images must be chosen again if restoring a draft.',
        'Send' => 'Send', 'Share' => 'Share',
        'Something went wrong. Please try again.' => 'Something went wrong. Please try again.',
        'Sorry, these dates/times are already booked!' => 'Sorry, these dates/times are already booked!',
        'Sport Type' => 'Sport Type', 'Start Time' => 'Start Time', 'Subject' => 'Subject',
        'Submit Appeal' => 'Submit Appeal', 'Submit Report' => 'Submit Report', 'Submit Ticket' => 'Submit Ticket',
        'Support' => 'Support', 'Support Tickets' => 'Support Tickets',
        'Tell other users about yourself...' => 'Tell other users about yourself...',
        'These dates/times are no longer available. Someone booked them just now!' => 'These dates/times are no longer available. Someone booked them just now!',
        'This card has expired. Please use a valid, unexpired card.' => 'This card has expired. Please use a valid, unexpired card.',
        'This is your listing' => 'This is your listing',
        'This ticket is closed and cannot be replied to.' => 'This ticket is closed and cannot be replied to.',
        'This user has no active listings.' => 'This user has no active listings.',
        'Ticket' => 'Ticket',
        'To book an item, sign in and browse categories, then select dates on the listing page. Admin must approve the query first.' => 'To book an item, sign in and browse categories, then select dates on the listing page. Admin must approve the query first.',
        'Top Listings Earnings' => 'Top Listings Earnings', 'Total Confirmed Earnings' => 'Total Confirmed Earnings',
        'Type a reply...' => 'Type a reply...',
        'Upload Additional Images (Optional)' => 'Upload Additional Images (Optional)',
        'User blocked.' => 'User blocked.', 'User unblocked.' => 'User unblocked.',
        'View' => 'View', 'View All' => 'View All', 'View Public Profile' => 'View Public Profile',
        'What is the cancellation policy?' => 'What is the cancellation policy?',
        'Why are you reporting this listing?' => 'Why are you reporting this listing?',
        'Why should the reports on this listing be deleted?' => 'Why should the reports on this listing be deleted?',
        'You are on the Waitlist!' => 'You are on the Waitlist!',
        'You can only cancel confirmed bookings at least 24 hours prior to the start time.' => 'You can only cancel confirmed bookings at least 24 hours prior to the start time.',
        'You can only leave a review after your booking has ended.' => 'You can only leave a review after your booking has ended.',
        'You can only review items you have rented and after the booking has completed.' => 'You can only review items you have rented and after the booking has completed.',
        'You cannot book in the past.' => 'You cannot book in the past.',
        'You cannot book your own listing.' => 'You cannot book your own listing.',
        'You cannot report your own listing.' => 'You cannot report your own listing.',
        'You have a 2-hour window after making a booking to easily cancel it from your Profile. Otherwise, you must contact the owner.' => 'You have a 2-hour window after making a booking to easily cancel it from your Profile. Otherwise, you must contact the owner.',
        'You have already reviewed this listing.' => 'You have already reviewed this listing.',
        'You have no active bookings.' => 'You have no active bookings.', 'You have no listings.' => 'You have no listings.',
        'You have no notifications.' => 'You have no notifications.', 'You have no open tickets.' => 'You have no open tickets.',
        'You have no past bookings.' => 'You have no past bookings.', 'You have no support tickets.' => 'You have no support tickets.',
        'Your Rently Verification Code' => 'Your Rently Verification Code',
        'Your booking has been submitted for admin pre-approval.' => 'Your booking has been submitted for admin pre-approval.',
        'e.g. Apple' => 'e.g. Apple', 'e.g. Bosch' => 'e.g. Bosch', 'e.g. Tesla' => 'e.g. Tesla',
    ],
    'he' => [
        'Cars' => 'רכבים', 'Apartments' => 'דירות', 'Equipment' => 'ציוד',
        'Electronics' => 'אלקטרוניקה', 'Sports field' => 'מגרש ספורט',
        'Home' => 'ראשי', 'Profile' => 'פרופיל', 'Add Listing' => 'הוסף פריט',
        'Admin Panel' => 'פאנל ניהול', 'Logout' => 'התנתק', 'Login' => 'התחבר',
        'Register' => 'הירשם', 'Rently - Smart Rental Platform' => 'רנטלי - פלטפורמת השכרה חכמה',
        'Find What You Need' => 'מצא בדיוק את מה שאתה צריך.',
        'Cars, Apartments' => 'רכבים, דירות, ציוד ועוד.',
        'Search keyword...' => 'חיפוש...', 'All Categories' => 'כל הקטגוריות',
        'All Cities' => 'כל הערים', 'Newest First' => 'החדשים ביותר',
        'Price: Low to High' => 'מחיר: מהנמוך לגבוה',
        'Price: High to Low' => 'מחיר: מהגבוה לנמוך',
        'Search' => 'חפש', 'View Details' => 'צפה בפרטים',
        'No listings found.' => 'לא נמצאו פריטים.',
        'Try adjusting' => 'נסה לשנות את מסנני החיפוש.',
        'My Profile' => 'הפרופיל שלי', 'Name' => 'שם:', 'Email' => 'אימייל:',
        'Phone' => 'טלפון:', 'My Bookings' => 'ההזמנות שלי', 'My Listings' => 'הפריטים שלי',
        'Add New Listing' => 'הוסף פריט חדש',
        'Rent out your items' => 'השכר את הפריטים שלך בבטחה.',
        'Title' => 'כותרת', 'Category' => 'קטגוריה', 'City' => 'עיר',
        'Price Per Day' => 'מחיר ליום (₪)', 'Price' => 'מחיר', 'Per' => 'לפי',
        'Day' => 'יום', 'Hour' => 'שעה',
        'Description' => 'תיאור', 'Image Upload' => 'העלאת תמונה (עד 2MB)',
        'Admin Dashboard' => 'לוח בקרה ניהולי',
        'Manage listings' => 'נהל פריטים, משתמשים ופעילות הפלטפורמה.',
        'Approve' => 'אשר', 'Delete' => 'מחק', 'Listing Details' => 'פרטי הפריט',
        'Owner' => 'בעלים', 'Status' => 'סטטוס', 'Actions' => 'פעולות',
        'Create an Account' => 'צור חשבון', 'Join Rently today!' => 'הצטרף לרנטלי עוד היום!',
        'Full Name' => 'שם מלא', 'Email Address' => 'כתובת אימייל', 'Password' => 'סיסמה',
        'Sign Up' => 'הרשמה', 'Already have an account?' => 'כבר יש לך חשבון?',
        'Verification' => 'אימות',
        'Enter the code we "sent" you.' => 'הזן את הקוד ש"שלחנו" לך.',
        'Verification Code' => 'קוד אימות', 'Verify & Login' => 'אימות והתחברות',
        'Welcome Back' => 'ברוך שובך',
        'Login to your Rently account.' => 'התחבר לחשבון הרנטלי שלך.',
        '2-Step Verification' => 'אימות דו-שלבי',
        "Don't have an account?" => 'אין לך חשבון?',
        'Book this item' => 'הזמן פריט זה', 'From Date' => 'מתאריך:',
        'To Date' => 'עד תאריך:', 'Confirm Booking' => 'אשר הזמנה',
        'Hosted by' => 'באירוח של', 'Pending' => 'ממתין', 'Approved' => 'מאושר',
        'Quick Links' => 'קישורים מהירים', 'Contact Us' => 'צור קשר',
        'Reviews' => 'ביקורות', 'Leave a Review' => 'כתוב ביקורת',
        'Rating' => 'דירוג', 'Your Comment' => 'התגובה שלך',
        'Submit Review' => 'שלח ביקורת', 'No reviews yet.' => 'אין ביקורות עדיין.',
        'Admins cannot book or review items.' => 'מנהלים אינם יכולים להזמין או לכתוב ביקורות.',
        'Rejected' => 'נדחה', 'Cancel' => 'בטל',
        'Booking Requests' => 'בקשות הזמנה', 'Reject' => 'דחה',
        'Booking approved!' => 'ההזמנה אושרה!',
        'Edit Profile' => 'ערוך פרופיל', 'Bio' => 'אודות', 'Profile Picture' => 'תמונת פרופיל',
        'Save Changes' => 'שמור שינויים', 'Profile updated successfully!' => 'הפרופיל עודכן בהצלחה!',
        'No bio yet.' => 'אין ביוגרפיה עדיין.',
        'Edit' => 'ערוך', 'Edit Listing' => 'ערוך פריט',
        'Upload New Image (optional)' => 'העלה תמונה חדשה (אופציונלי)',
        'Listing updated successfully!' => 'הפריט עודכן בהצלחה!',
        'No bookings yet.' => 'אין הזמנות עדיין.', 'No listings yet.' => 'אין פריטים עדיין.',
        'Add one!' => 'הוסף אחד!',
        'Checkout' => 'תשלום', 'Payment Details' => 'פרטי תשלום',
        'Cardholder Name' => 'שם בעל הכרטיס', 'Card Number' => 'מספר כרטיס',
        'Expiry Date' => 'תאריך תפוגה', 'Pay' => 'שלם', 'Total' => 'סה"כ',
        'Secure payment simulation for demo purposes.' => 'סימולציית תשלום מאובטחת למטרות הדגמה.',
        'Booking Submitted!' => 'ההזמנה נשלחה!',
        'Your booking request has been sent to the owner for approval.' => 'בקשת ההזמנה שלך נשלחה לבעלים לאישור.',
        'View My Bookings' => 'צפה בהזמנות שלי',
        'Please fill all payment fields.' => 'מלא את כל שדות התשלום.',
        'Invalid card number.' => 'מספר כרטיס לא תקין.',
        'These dates are no longer available. Someone booked them just now!' => 'התאריכים כבר לא זמינים!',
        'Proceed to Checkout' => 'המשך לתשלום',
        'Sorry, these dates are already booked!' => 'סליחה, תאריכים אלו כבר תפוסים!',
        'End date must be after start date.' => 'תאריך הסיום חייב להיות אחרי תאריך ההתחלה.',
        'Please login to book.' => 'אנא התחבר כדי להזמין.',
        'Forgot Password' => 'שכחתי סיסמה', 'Forgot Password?' => 'שכחת סיסמה?',
        'Enter your email to receive a reset code.' => 'הזן את האימייל שלך לקבלת קוד איפוס.',
        'Send Reset Code' => 'שלח קוד איפוס', 'Back to Login' => 'חזור להתחברות',
        'Reset Password' => 'איפוס סיסמה', 'New Password' => 'סיסמה חדשה',
        'Password Updated!' => 'הסיסמה עודכנה!',
        'Password reset successfully!' => 'הסיסמה אופסה בהצלחה!',
        'No account found with that email.' => 'לא נמצא חשבון עם אימייל זה.',
        'Invalid reset code.' => 'קוד איפוס לא תקין.',
        'My Favorites' => 'המועדפים שלי', 'No favorites yet.' => 'אין מועדפים עדיין.',
        'Browse listings and click the heart icon to save items here.' => 'עיין בפריטים ולחץ על הלב כדי לשמור כאן.',
        'Browse Listings' => 'עיין בפריטים', 'Add to Favorites' => 'הוסף למועדפים',
        'Remove' => 'הסר',
        'You May Also Like' => 'אולי יעניין אותך גם', 'Location' => 'מיקום',
        '/ day' => '/ יום', '/ hour' => '/ שעה', 'days' => 'ימים', 'hours' => 'שעות',
        'Check-in' => 'כניסה', 'Check-out' => 'יציאה',
        'Min ₪' => 'מינימום ₪', 'Max ₪' => 'מקסימום ₪',
        'Users' => 'משתמשים', 'Listings' => 'פריטים', 'Bookings' => 'הזמנות',
        'Revenue' => 'הכנסות', 'Block' => 'חסום', 'Unblock' => 'בטל חסימה',
        'Role' => 'תפקיד', 'Image' => 'תמונה',
        'Your account has been blocked. Contact support.' => 'החשבון שלך נחסם. צור קשר עם התמיכה.',
        'Invalid email or password.' => 'אימייל או סיסמה שגויים.',
        'Invalid verification code!' => 'קוד אימות שגוי!',
        'Review added successfully!' => 'הביקורת נוספה בהצלחה!',
        'Failed to add review.' => 'נכשל בהוספת ביקורת.',
        'Listing added successfully! Waiting for admin approval.' => 'הפריט נוסף! ממתין לאישור מנהל.',
        'The smart way to rent anything. Cars, apartments, equipment and more — all in one platform.' => 'הדרך החכמה לשכור הכל. רכבים, דירות, ציוד ועוד — הכל בפלטפורמה אחת.',
        'Categories' => 'קטגוריות',
        'Show Filters' => 'הצג מסננים', 'Hide Filters' => 'הסתר מסננים',
        'Apply Filters' => 'החל מסננים', 'Sort' => 'מיון',
        'results found' => 'תוצאות נמצאו',
        'Renter' => 'שוכר', 'Dates' => 'תאריכים', 'Amount' => 'סכום',
        'Filter by Date' => 'סנן לפי תאריך', 'All Time' => 'הכל', 'Today' => 'היום',
        'Last 7 Days' => '7 ימים אחרונים', 'Last 30 Days' => '30 ימים אחרונים', 'Last Year' => 'שנה אחרונה',
        'Custom' => 'מותאם אישית', 'Start Date' => 'תאריך התחלה', 'End Date' => 'תאריך סיום', 'Apply' => 'החל',
        'A login verification code has been sent to your email.' => 'קוד אימות להתחברות נשלח לאימייל שלך.',
        'A password reset code has been sent to your email.' => 'קוד לאיפוס סיסמה נשלח לאימייל שלך.',
        'A verification code has been sent to your email.' => 'קוד אימות נשלח לאימייל שלך.',
        'Accept' => 'קבל', 'Active Bookings' => 'הזמנות פעילות',
        'Admins cannot book items.' => 'מנהלים לא יכולים להזמין פריטים.',
        'Admins cannot leave reviews.' => 'מנהלים לא יכולים לכתוב ביקורות.',
        'All caught up!' => 'הכל עדכני!', 'Analytics' => 'ניתוח נתונים',
        'Answered' => 'נענה', 'Any' => 'הכל',
        'Appeal Reports' => 'ערעור על דיווחים',
        'Appeal submitted successfully as a support ticket.' => 'הערעור הוגש בהצלחה כפניית תמיכה.',
        'Are you sure you want to cancel this booking?' => 'האם אתה בטוח שברצונך לבטל את ההזמנה?',
        'Are you sure you want to delete all reports for this listing?' => 'האם אתה בטוח שברצונך למחוק את כל הדיווחים על פריט זה?',
        'Are you sure you want to delete this listing?' => 'האם אתה בטוח שברצונך למחוק פריט זה?',
        'Avatar Upload' => 'העלאת תמונת פרופיל', 'Back' => 'חזור',
        'Because these dates/times are pending approval, you joined the waitlist. If they become available, your slot will promote automatically.' => 'מכיוון שהתאריכים/השעות הללו ממתינים לאישור, הצטרפת לרשימת ההמתנה. אם יתפנו, המקום שלך יאושר אוטומטית.',
        'Bio / Description' => 'אודות / תיאור',
        'Booking approved to pending owner.' => 'ההזמנה אושרה והועברה לבעלים לאישור.',
        'Booking cancelled successfully.' => 'ההזמנה בוטלה בהצלחה.',
        'Booking rejected.' => 'ההזמנה נדחתה.',
        'Booking request approved!' => 'בקשת ההזמנה אושרה!',
        'Booking request rejected.' => 'בקשת ההזמנה נדחתה.',
        'Bookings Distribution' => 'התפלגות הזמנות',
        'Brief summary of the issue...' => 'תקציר קצר של הבעיה...',
        'CSRF token verification failed.' => 'אימות אבטחה (CSRF) נכשל.',
        'Cancel Booking' => 'בטל הזמנה',
        'Cannot accept. Overlapping dates/hours have already been approved!' => 'לא ניתן לאשר. תאריכים/שעות חופפים כבר אושרו!',
        'Car Make' => 'יצרן הרכב', 'Category Share' => 'התפלגות קטגוריות',
        'Close Ticket' => 'סגור פנייה', 'Close this ticket?' => 'לסגור פנייה זו?',
        'Closed' => 'סגור',
        'Contact details are private and will be visible once you have an approved booking with this user.' => 'פרטי הקשר פרטיים ויוצגו רק לאחר הזמנה מאושרת עם משתמש זה.',
        'Copied!' => 'הועתק!',
        'Current Additional Images' => 'תמונות נוספות קיימות', 'Current Image' => 'תמונה נוכחית',
        'Database error: ' => 'שגיאת מסד נתונים: ', 'Date' => 'תאריך',
        'Delete Reports' => 'מחק דיווחים',
        'Describe your problem in detail...' => 'תאר את הבעיה בפירוט...',
        'Dismiss' => 'התעלם',
        'Duplicate email. This email is already registered.' => 'אימייל כפול. כתובת זו רשומה כבר במערכת.',
        'Electronics Brand' => 'מותג האלקטרוניקה', 'End Time' => 'שעת סיום',
        'End time/date must be after start time/date.' => 'שעת/תאריך הסיום חייב להיות אחרי שעת/תאריך ההתחלה.',
        'Enter the code we sent you.' => 'הזן את הקוד שנשלח אליך.',
        'Equipment Brand' => 'מותג הציוד',
        'Failed to copy link.' => 'העתקת הקישור נכשלה.',
        'Failed to move uploaded file.' => 'העברת הקובץ שהועלה נכשלה.',
        'Failed to process booking. Database error: ' => 'עיבוד ההזמנה נכשל. שגיאת מסד נתונים: ',
        'Failed to save listing. Database error: ' => 'שמירת הפריט נכשלה. שגיאת מסד נתונים: ',
        'Failed to send verification email. Please contact support.' => 'שליחת אימייל האימות נכשלה. אנא צור קשר עם התמיכה.',
        'Failed to submit appeal.' => 'שליחת הערעור נכשלה.',
        'Failed to submit report.' => 'שליחת הדיווח נכשלה.',
        'Failed to update profile.' => 'עדכון הפרופיל נכשל.',
        'Go to My Listings' => 'עבור לפריטים שלי',
        'Hello! I am the Rently Assistant. How can I help you today?' => 'שלום! אני העוזר של רנטלי. איך אפשר לעזור לך היום?',
        'Here is your verification code:' => 'הנה קוד האימות שלך:',
        'How do I book?' => 'איך מזמינים?', 'How do I contact admin?' => 'איך פונים למנהל?',
        'If you need admin help, please open a Support Ticket from your Profile or the top menu!' => 'אם אתה צריך עזרה ממנהל, אנא פתח פנייה לתמיכה מהפרופיל שלך או מהתפריט העליון!',
        'Image deleted successfully.' => 'התמונה נמחקה בהצלחה.',
        'Image is too large. Max 2MB.' => 'התמונה גדולה מדי. מקסימום 2MB.',
        'Image not found.' => 'התמונה לא נמצאה.',
        'Incoming Booking Requests' => 'בקשות הזמנה נכנסות',
        'Invalid email.' => 'אימייל לא תקין.',
        'Invalid expiry date. Please use the MM/YY format.' => 'תאריך תפוגה לא תקין. יש להשתמש בפורמט MM/YY.',
        'Invalid image format. Only JPG, PNG, and WebP are allowed.' => 'פורמט תמונה לא תקין. מותר רק JPG, PNG ו-WebP.',
        'Invalid phone number. It must be exactly 10 digits.' => 'מספר טלפון לא תקין. חייב להיות בדיוק 10 ספרות.',
        'Listing approved.' => 'הפריט אושר.',
        'Listing deactivated (historical booking data preserved).' => 'הפריט הושבת (נתוני ההזמנות ההיסטוריים נשמרו).',
        'Listing deactivated (history preserved).' => 'הפריט הושבת (ההיסטוריה נשמרה).',
        'Listing deleted successfully.' => 'הפריט נמחק בהצלחה.', 'Listing deleted.' => 'הפריט נמחק.',
        'Listing updated successfully! Status reset to pending for admin approval.' => 'הפריט עודכן בהצלחה! הסטטוס אופס לממתין לאישור מנהל.',
        'Manage systems' => 'ניהול המערכת', 'Mark all as read' => 'סמן הכל כנקרא',
        'Message' => 'הודעה', 'Min Rooms' => 'מס\' חדרים מינימלי',
        'Most Active Renters' => 'השוכרים הפעילים ביותר',
        'My Support Tickets' => 'פניות התמיכה שלי', 'My Tickets' => 'הפניות שלי',
        'Name and Email cannot be empty.' => 'שם ואימייל לא יכולים להיות ריקים.',
        'Need help?' => 'צריך עזרה?', 'New %s' => '%s חדשים',
        'No bio provided.' => 'לא הוזנה ביוגרפיה.',
        'No bookings found matching these criteria.' => 'לא נמצאו הזמנות התואמות לקריטריונים אלו.',
        'No incoming booking requests.' => 'אין בקשות הזמנה נכנסות.',
        'No listings found matching these criteria.' => 'לא נמצאו פריטים התואמים לקריטריונים אלו.',
        'No reports found matching these criteria.' => 'לא נמצאו דיווחים התואמים לקריטריונים אלו.',
        'No support tickets found matching these criteria.' => 'לא נמצאו פניות תמיכה התואמות לקריטריונים אלו.',
        'No users found matching these criteria.' => 'לא נמצאו משתמשים התואמים לקריטריונים אלו.',
        'Notifications' => 'התראות',
        'Occupied hours on this date:' => 'שעות תפוסות בתאריך זה:',
        'Open' => 'פתוח', 'Open Support Center' => 'פתח את מרכז התמיכה',
        'Open a New Ticket' => 'פתח פנייה חדשה', 'Opened on' => 'נפתח בתאריך',
        'Owner Contact Information:' => 'פרטי התקשרות עם הבעלים:',
        'Password must be at least 6 characters.' => 'הסיסמה חייבת להיות באורך של 6 תווים לפחות.',
        'Past Bookings' => 'הזמנות קודמות', 'Phone Number' => 'מספר טלפון',
        'Please upload an image.' => 'אנא העלה תמונה.',
        'Price must be a positive number.' => 'המחיר חייב להיות מספר חיובי.',
        'Profile Settings' => 'הגדרות פרופיל',
        'Profile updated successfully.' => 'הפרופיל עודכן בהצלחה.',
        'Rating must be between 1 and 5.' => 'הדירוג חייב להיות בין 1 ל-5.',
        'Reject this booking?' => 'לדחות הזמנה זו?', 'Remove from favorites?' => 'להסיר מהמועדפים?',
        'Renter Contact Information:' => 'פרטי התקשרות עם השוכר:',
        'Report Listing' => 'דווח על הפריט', 'Report dismissed.' => 'הדיווח בוטל.',
        'Report marked as resolved.' => 'הדיווח סומן כטופל.',
        'Report submitted successfully.' => 'הדיווח נשלח בהצלחה.',
        'Report this Listing' => 'דווח על פריט זה', 'Reported' => 'דווח', 'Reports' => 'דיווחים',
        'Required field missing.' => 'שדה חובה חסר.', 'Resolve' => 'טפל',
        'Save Profile Settings' => 'שמור הגדרות פרופיל', 'Search Results' => 'תוצאות חיפוש',
        'Select Date' => 'בחר תאריך',
        'Selected images must be chosen again if restoring a draft.' => 'יש לבחור מחדש את התמונות שנבחרו אם משחזרים טיוטה.',
        'Send' => 'שלח', 'Share' => 'שתף',
        'Something went wrong. Please try again.' => 'משהו השתבש. אנא נסה שוב.',
        'Sorry, these dates/times are already booked!' => 'מצטערים, התאריכים/השעות הללו כבר תפוסים!',
        'Sport Type' => 'סוג הספורט', 'Start Time' => 'שעת התחלה', 'Subject' => 'נושא',
        'Submit Appeal' => 'שלח ערעור', 'Submit Report' => 'שלח דיווח', 'Submit Ticket' => 'שלח פנייה',
        'Support' => 'תמיכה', 'Support Tickets' => 'פניות תמיכה',
        'Tell other users about yourself...' => 'ספר למשתמשים אחרים על עצמך...',
        'These dates/times are no longer available. Someone booked them just now!' => 'התאריכים/השעות הללו לא זמינים יותר. מישהו הזמין אותם ממש עכשיו!',
        'This card has expired. Please use a valid, unexpired card.' => 'הכרטיס הזה פג תוקף. אנא השתמש בכרטיס תקף שלא פג תוקפו.',
        'This is your listing' => 'זהו הפריט שלך',
        'This ticket is closed and cannot be replied to.' => 'פנייה זו סגורה ולא ניתן להשיב עליה.',
        'This user has no active listings.' => 'למשתמש זה אין פריטים פעילים.',
        'Ticket' => 'פנייה',
        'To book an item, sign in and browse categories, then select dates on the listing page. Admin must approve the query first.' => 'כדי להזמין פריט, התחבר ועיין בקטגוריות, ולאחר מכן בחר תאריכים בעמוד הפריט. על המנהל לאשר את הבקשה תחילה.',
        'Top Listings Earnings' => 'הפריטים המובילים בהכנסות', 'Total Confirmed Earnings' => 'סה"כ הכנסות מאושרות',
        'Type a reply...' => 'הקלד תשובה...',
        'Upload Additional Images (Optional)' => 'העלה תמונות נוספות (אופציונלי)',
        'User blocked.' => 'המשתמש נחסם.', 'User unblocked.' => 'חסימת המשתמש הוסרה.',
        'View' => 'צפה', 'View All' => 'צפה בהכל', 'View Public Profile' => 'צפה בפרופיל הציבורי',
        'What is the cancellation policy?' => 'מה מדיניות הביטולים?',
        'Why are you reporting this listing?' => 'מדוע אתה מדווח על פריט זה?',
        'Why should the reports on this listing be deleted?' => 'מדוע יש למחוק את הדיווחים על פריט זה?',
        'You are on the Waitlist!' => 'אתה ברשימת ההמתנה!',
        'You can only cancel confirmed bookings at least 24 hours prior to the start time.' => 'ניתן לבטל הזמנות מאושרות רק לפחות 24 שעות לפני שעת ההתחלה.',
        'You can only leave a review after your booking has ended.' => 'ניתן להשאיר ביקורת רק לאחר שההזמנה הסתיימה.',
        'You can only review items you have rented and after the booking has completed.' => 'ניתן לכתוב ביקורת רק על פריטים ששכרת ולאחר שההזמנה הושלמה.',
        'You cannot book in the past.' => 'לא ניתן להזמין בעבר.',
        'You cannot book your own listing.' => 'לא ניתן להזמין את הפריט שלך.',
        'You cannot report your own listing.' => 'לא ניתן לדווח על הפריט שלך.',
        'You have a 2-hour window after making a booking to easily cancel it from your Profile. Otherwise, you must contact the owner.' => 'יש לך חלון של שעתיים מרגע ההזמנה לבטל אותה בקלות מהפרופיל שלך. אחרי כן, יש לפנות לבעלים.',
        'You have already reviewed this listing.' => 'כבר כתבת ביקורת על פריט זה.',
        'You have no active bookings.' => 'אין לך הזמנות פעילות.', 'You have no listings.' => 'אין לך פריטים.',
        'You have no notifications.' => 'אין לך התראות.', 'You have no open tickets.' => 'אין לך פניות פתוחות.',
        'You have no past bookings.' => 'אין לך הזמנות קודמות.', 'You have no support tickets.' => 'אין לך פניות תמיכה.',
        'Your Rently Verification Code' => 'קוד האימות שלך לרנטלי',
        'Your booking has been submitted for admin pre-approval.' => 'בקשת ההזמנה שלך נשלחה לאישור מקדים של המנהל.',
        'e.g. Apple' => 'לדוגמה: Apple', 'e.g. Bosch' => 'לדוגמה: Bosch', 'e.g. Tesla' => 'לדוגמה: Tesla',
    ]
];
?>
